// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA664JuvyLjtRDq2oEYCORyJRlErqXPMvY',
    appId: '1:525779714660:web:3493160b0fd5ef5a8a1571',
    messagingSenderId: '525779714660',
    projectId: 'chat-app-66f7c',
    authDomain: 'chat-app-66f7c.firebaseapp.com',
    storageBucket: 'chat-app-66f7c.appspot.com',
    measurementId: 'G-Z061W0F326',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrSJg3k3Np64UKwQVuMx0bKKt0dPYn28',
    appId: '1:525779714660:android:6f7a6ccb1d3cffec8a1571',
    messagingSenderId: '525779714660',
    projectId: 'chat-app-66f7c',
    storageBucket: 'chat-app-66f7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Cu59IhkUyPEIFFxiRs7nFuMwPcxkKmQ',
    appId: '1:525779714660:ios:a914e62adbd975948a1571',
    messagingSenderId: '525779714660',
    projectId: 'chat-app-66f7c',
    storageBucket: 'chat-app-66f7c.appspot.com',
    iosClientId: '525779714660-k1rk5ob1cjt446ffr4trbnbkf6u9v7o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Cu59IhkUyPEIFFxiRs7nFuMwPcxkKmQ',
    appId: '1:525779714660:ios:a914e62adbd975948a1571',
    messagingSenderId: '525779714660',
    projectId: 'chat-app-66f7c',
    storageBucket: 'chat-app-66f7c.appspot.com',
    iosClientId: '525779714660-k1rk5ob1cjt446ffr4trbnbkf6u9v7o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
